//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ReinertProject.Module.BusinessObjects.Database
{

    [Persistent(@"Mieter")]
    public partial class MieterClass : XPLiteObject
    {
        int fIDProperty;
        [Key]
        [Persistent(@"ID")]
        public int IDProperty
        {
            get { return fIDProperty; }
            set { SetPropertyValue<int>(nameof(IDProperty), ref fIDProperty, value); }
        }
        string fNameProperty;
        [Size(255)]
        [Persistent(@"Name")]
        public string NameProperty
        {
            get { return fNameProperty; }
            set { SetPropertyValue<string>(nameof(NameProperty), ref fNameProperty, value); }
        }
        string fVornameProperty;
        [Size(255)]
        [Persistent(@"Vorname")]
        public string VornameProperty
        {
            get { return fVornameProperty; }
            set { SetPropertyValue<string>(nameof(VornameProperty), ref fVornameProperty, value); }
        }
        string fPersoNummerProperty;
        [Size(255)]
        [Persistent(@"PersoNummer")]
        public string PersoNummerProperty
        {
            get { return fPersoNummerProperty; }
            set { SetPropertyValue<string>(nameof(PersoNummerProperty), ref fPersoNummerProperty, value); }
        }
        bool fProblemeProperty;
        [Persistent(@"Probleme")]
        public bool ProblemeProperty
        {
            get { return fProblemeProperty; }
            set { SetPropertyValue<bool>(nameof(ProblemeProperty), ref fProblemeProperty, value); }
        }
        DateTime fMieterSeitProperty;
        [Persistent(@"MieterSeit")]
        public DateTime MieterSeitProperty
        {
            get { return fMieterSeitProperty; }
            set { SetPropertyValue<DateTime>(nameof(MieterSeitProperty), ref fMieterSeitProperty, value); }
        }
    }

}
