//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ReinertProject.Module.BusinessObjects.Database
{

    [Persistent(@"Reparatur")]
    public partial class ReparaturClass : XPLiteObject
    {
        int fIDProperty;
        [Key]
        [Persistent(@"ID")]
        public int IDProperty
        {
            get { return fIDProperty; }
            set { SetPropertyValue<int>(nameof(IDProperty), ref fIDProperty, value); }
        }
        decimal fBetragProperty;
        [Persistent(@"Betrag")]
        public decimal BetragProperty
        {
            get { return fBetragProperty; }
            set { SetPropertyValue<decimal>(nameof(BetragProperty), ref fBetragProperty, value); }
        }
        string fBezeichnungProperty;
        [Size(255)]
        [Persistent(@"Bezeichnung")]
        public string BezeichnungProperty
        {
            get { return fBezeichnungProperty; }
            set { SetPropertyValue<string>(nameof(BezeichnungProperty), ref fBezeichnungProperty, value); }
        }
        DateTime fDatumProperty;
        [Persistent(@"Datum")]
        public DateTime DatumProperty
        {
            get { return fDatumProperty; }
            set { SetPropertyValue<DateTime>(nameof(DatumProperty), ref fDatumProperty, value); }
        }
        int fWohnungProperty;
        [Persistent(@"Wohnung")]
        public int WohnungProperty
        {
            get { return fWohnungProperty; }
            set { SetPropertyValue<int>(nameof(WohnungProperty), ref fWohnungProperty, value); }
        }
    }

}
