//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ReinertProject.Module.BusinessObjects.Database
{

    [Persistent(@"WohnungMieter")]
    public partial class WohnungMieterClass : XPLiteObject
    {
        int fIDProperty;
        [Key]
        [Persistent(@"ID")]
        public int IDProperty
        {
            get { return fIDProperty; }
            set { SetPropertyValue<int>(nameof(IDProperty), ref fIDProperty, value); }
        }
        int fWohnungProperty;
        [Persistent(@"Wohnung")]
        public int WohnungProperty
        {
            get { return fWohnungProperty; }
            set { SetPropertyValue<int>(nameof(WohnungProperty), ref fWohnungProperty, value); }
        }
        int fMieterProperty;
        [Persistent(@"Mieter")]
        public int MieterProperty
        {
            get { return fMieterProperty; }
            set { SetPropertyValue<int>(nameof(MieterProperty), ref fMieterProperty, value); }
        }
    }

}
