//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ReinertProject.Module.BusinessObjects.Database
{

    public partial class Mandant : XPLiteObject
    {
        int fID;
        [Key]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(255)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fVorname;
        [Size(255)]
        public string Vorname
        {
            get { return fVorname; }
            set { SetPropertyValue<string>(nameof(Vorname), ref fVorname, value); }
        }
        string fStrasse;
        [Size(255)]
        public string Strasse
        {
            get { return fStrasse; }
            set { SetPropertyValue<string>(nameof(Strasse), ref fStrasse, value); }
        }
        int fHausnummer;
        public int Hausnummer
        {
            get { return fHausnummer; }
            set { SetPropertyValue<int>(nameof(Hausnummer), ref fHausnummer, value); }
        }
        string fPostleitzahl;
        [Size(255)]
        public string Postleitzahl
        {
            get { return fPostleitzahl; }
            set { SetPropertyValue<string>(nameof(Postleitzahl), ref fPostleitzahl, value); }
        }
        string fOrt;
        [Size(255)]
        public string Ort
        {
            get { return fOrt; }
            set { SetPropertyValue<string>(nameof(Ort), ref fOrt, value); }
        }
        string fLand;
        [Size(255)]
        public string Land
        {
            get { return fLand; }
            set { SetPropertyValue<string>(nameof(Land), ref fLand, value); }
        }
    }

}
