//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Validation;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.ConditionalAppearance;
using System.ComponentModel.DataAnnotations.Schema;
using DevExpress.ExpressApp.Model;
namespace ReinertProject.Module.BusinessObjects.Database
{

    public partial class Reparatur : XPLiteObject
    {
        int fID;
        [Key]
        [RuleRequiredField, RuleUniqueValue]
        [XafDisplayName("Identifier")]


        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        decimal fBetrag;
        [RuleRequiredField]

        public decimal Betrag
        {
            get { return fBetrag; }
            set { SetPropertyValue<decimal>(nameof(Betrag), ref fBetrag, value); }
        }
        string fBezeichnung;
        [RuleRequiredField]

        [Size(255)]
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>(nameof(Bezeichnung), ref fBezeichnung, value); }
        }
        DateTime fDatum;
        [RuleRequiredField]

        public DateTime Datum
        {
            get { return fDatum; }
            set { SetPropertyValue<DateTime>(nameof(Datum), ref fDatum, value); }
        }
        int fWohnung;
        public int Wohnung
        {
            get { return fWohnung; }
            set { SetPropertyValue<int>(nameof(Wohnung), ref fWohnung, value); }
        }

        Status fstatus;
        public Status Status
        {
            get => fstatus;
            set => SetPropertyValue(nameof(Status), ref fstatus, value);
        }

        [NotMapped]
        [ModelDefault("DisplayFormat" , "{0:c")]
        public decimal Amount
        {
            get { return fBetrag; }
        }



    }
    public enum Status
    {
        ToDo = 0,
        InProgress = 1,
        Completed = 2,
        Error = 3

    }

}
